name: Hello
on:
  push:
    branches:
      - feature**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo only feature branch

